spring:
  kafka:
    bootstrap-servers: artur:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: <database_url>
    username: <database_username>
    password: <database_password>
