spring:
  kafka:
    bootstrap-servers: <server>
  datasource:
    driver-class-name: org.postgresql.Driver
    url: <database_url>
    username: <database_username>
    password: <database_password>
