spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres #<database_username>
    password: 1 #<database_password>
    url: jdbc:postgresql://localhost:5432/db #<database_url>
  kafka:
    bootstrap-servers: artur:9092

token:
  jwtSecret: secret #<secret>
  jwtIssuer: ITAcademy #<issuer>

userdetailservice:
  url: http://localhost:8080/users/userDetails/mail/
server:
  port: 8090