spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: <database_username>
    password: <database_password>
    url: <database_url>
  kafka:
    bootstrap-servers: <server>

token:
  jwtSecret: <secret>
  jwtIssuer: <issuer>

userdetailservice:
  url: <url>