spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: <database_username>
    password: <database_password>
    url: <database_url>


token:
  jwtSecret: <secret>
  jwtIssuer: <issuer>

userdetailservice:
  url: <url>
