spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres #<database_username>
    password: 1 #<database_password>
    url: jdbc:postgresql://localhost:5432/db #<database_url>
  kafka:
    bootstrap-servers: artur:9092
email:
  sendUrl: <sendurl>
  verifyUrl: <verifyurl>

token:
  jwtSecret: secret #<jwt_secret>
  jwtIssuer: ITAcademy #<jwt_issuer>
